vich_uploader:
  db_driver: orm

  mappings:
    artisticWorks:
      uri_prefix: /images/artisticWorks
      upload_destination: "%kernel.project_dir%/public/images/artisticWorks"

    avatars:
      uri_prefix: /images/avatars
      upload_destination: "%kernel.project_dir%/public/images/avatars"
